# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# build stage
FROM node:lts-alpine as build-stage

RUN apk update && apk add python g++ git make && rm -rf /var/cache/apk/*
WORKDIR /app
COPY examples/gameroom/gameroom-app/package*.json ./
RUN npm install
COPY examples/gameroom/gameroom-app/ .
COPY /libsplinter/protos ./protos
ARG VUE_APP_BRAND
RUN npm run build-${VUE_APP_BRAND}
COPY VERSION .
WORKDIR ./dist
ARG REPO_VERSION
RUN tar c -z . -f ../gameroom_ui_${VUE_APP_BRAND}_v${REPO_VERSION}.tar.gz

# Log the commit hash
COPY .git/ /tmp/.git/
WORKDIR /tmp
RUN git rev-parse HEAD > /commit-hash

# prod stage
FROM httpd:2.4 as prod-stage

COPY --from=build-stage /app/gameroom_ui_*.tar.gz /tmp
COPY --from=build-stage /commit-hash /commit-hash
RUN tar -xzvf /tmp/gameroom_ui_*.tar.gz -C /usr/local/apache2/htdocs/

RUN echo "\
\n\
ServerName gameroom-app\n\
AddDefaultCharset utf-8\n\
LoadModule proxy_module modules/mod_proxy.so\n\
LoadModule proxy_http_module modules/mod_proxy_http.so\n\
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so\n\
ProxyPass /api http://gameroomd-\${VUE_APP_BRAND}:8000\n\
ProxyPassReverse /api http://gameroomd-\${VUE_APP_BRAND}:8000\n\
ProxyPass /ws ws://gameroomd-\${VUE_APP_BRAND}:8000\n\
ProxyPassReverse /ws ws://gameroomd-\${VUE_APP_BRAND}:8000\n\
\n\
" >>/usr/local/apache2/conf/httpd.conf

EXPOSE 80/tcp
