# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM splintercommunity/splinter-dev as BUILDER

# Copy over source files
COPY examples/private_counter/protos /build/examples/private_counter/protos
COPY examples/private_counter/service /build/examples/private_counter/service
COPY libsplinter /build/libsplinter

# Build the package
WORKDIR /build/examples/private_counter/service
ARG REPO_VERSION
ARG CARGO_ARGS
RUN sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${REPO_VERSION}\"/" Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION $CARGO_ARGS

# Log the commit hash
COPY .git/ /tmp/.git/
WORKDIR /tmp
RUN git rev-parse HEAD > /commit-hash

# -------------=== private_xo docker build ===-------------
FROM ubuntu:bionic

ARG CARGO_ARGS
RUN echo "CARGO_ARGS = '$CARGO_ARGS'" > CARGO_ARGS

COPY --from=BUILDER /build/target/debian/private-counter-service*.deb /tmp
COPY --from=BUILDER /commit-hash /commit-hash

RUN apt-get update \
 && dpkg --unpack /tmp/private-counter-service*.deb \
 && apt-get -f -y install

EXPOSE 8000

CMD ["private-counter"]
