# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM splintercommunity/splinter-dev as BUILDER

COPY protos/ /build/protos/
COPY libsplinter/src /build/libsplinter/src
COPY examples/private_xo /build/examples/private_xo

# Build the package
WORKDIR /build/examples/private_xo
ARG REPO_VERSION
ARG CARGO_ARGS
RUN sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${REPO_VERSION}\"/" Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION $CARGO_ARGS

# -------------=== private_xo docker build ===-------------
FROM ubuntu:bionic

ARG CARGO_ARGS
RUN echo "CARGO_ARGS = '$CARGO_ARGS'" > CARGO_ARGS

COPY --from=BUILDER /build/target/debian/private-xo-service*.deb /tmp

RUN apt-get update \
 && dpkg --unpack /tmp/private-xo-service*.deb \
 && apt-get -f -y install

EXPOSE 8000

CMD ["private-xo"]
