# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:bionic as BUILDER

# Install base dependencies
RUN apt-get update \
 && apt-get install -y \
    curl \
    gcc \
    libssl-dev \
    libzmq3-dev \
    pkg-config \
    unzip \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ENV PATH=$PATH:/root/.cargo/bin

# Install Rust
RUN curl https://sh.rustup.rs -sSf > /usr/bin/rustup-init \
 && chmod +x /usr/bin/rustup-init \
 && rustup-init -y

# Install protoc
RUN curl -OLsS https://github.com/google/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip \
    && unzip -o protoc-3.7.1-linux-x86_64.zip -d /usr/local \
    && rm protoc-3.7.1-linux-x86_64.zip

# Copy dependencies
COPY protos /build/protos
COPY libsplinter /build/libsplinter

# Create empty cargo project
WORKDIR /build/examples
RUN USER=root cargo new --bin private_xo

# Copy over Cargo.toml file
COPY examples/private_xo/Cargo.toml /build/examples/private_xo/Cargo.toml

# Do a release build to cache dependencies
WORKDIR /build/examples/private_xo
RUN cargo build --release

# Remove the auto-generated .rs files and the built files
RUN rm src/*.rs
RUN rm target/release/private-xo* target/release/deps/private_xo*

# Copy over source files
COPY ./examples/private_xo/protos /build/examples/private_xo/protos
COPY ./examples/private_xo/build.rs /build/examples/private_xo/build.rs
COPY ./examples/private_xo/src /build/examples/private_xo/src
COPY libsplinter/src /build/libsplinter/src
COPY protos/ /build/protos/

RUN cargo install cargo-deb

# Build the package
ARG REPO_VERSION
RUN sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${REPO_VERSION}\"/" Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION

# -------------=== private_xo docker build ===-------------
FROM ubuntu:bionic

COPY --from=BUILDER /build/examples/private_xo/target/debian/private-xo-service*.deb /tmp

RUN apt-get update \
 && dpkg -i /tmp/private-xo-service*.deb || true \
 && apt-get -f -y install

EXPOSE 8000

CMD ["private-xo"]
