# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM splintercommunity/splinter-dev as BUILDER

# Copy over source files
COPY client /build/client
COPY protos /build/protos
COPY libsplinter /build/libsplinter
COPY cli /build/cli

# Build the project
WORKDIR /build/cli
ARG REPO_VERSION
ARG CARGO_ARGS
RUN sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${REPO_VERSION}\"/" Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION $CARGO_ARGS

# -------------=== splinter cli docker build ===-------------

FROM ubuntu:bionic

COPY --from=builder /build/target/debian/splinter-cli_*.deb /tmp

RUN apt-get update \
 && dpkg --unpack /tmp/splinter-cli_*.deb \
 && apt-get -f -y install
