# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM splintercommunity/splinter-dev as BUILDER

# Copy over source files
COPY examples/private_counter/cli/src src

# Build the project
WORKDIR examples/private_counter/cli
ARG REPO_VERSION
RUN sed -i -e s/version.*$/version\ =\ \"${REPO_VERSION}\"/ Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION

# -------------=== private_counter docker build ===-------------
FROM ubuntu:bionic

COPY --from=BUILDER /build/target/debian/private-counter-cli*.deb /tmp

RUN apt-get update \
 && dpkg -i /tmp/private-counter-cli*.deb || true \
 && apt-get -f -y install

EXPOSE 8000

CMD ["pcounter"]
