# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -------------=== splinterd docker build ===-------------

FROM splintercommunity/splinter-dev as BUILDER

COPY protos /build/protos
COPY libsplinter /build/libsplinter
COPY splinterd/ /build/splinterd

# Build the package
WORKDIR /build/splinterd
ARG REPO_VERSION
RUN sed -i -e s/version.*$/version\ =\ \"${REPO_VERSION}\"/ Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION

# -------------=== splinterd docker build ===-------------

FROM ubuntu:bionic

COPY --from=builder /build/target/debian/splinter-daemon*.deb /tmp

RUN apt-get update \
 && dpkg --unpack /tmp/splinter-daemon*.deb \
 && apt-get -f -y install
