# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -------------=== splinterd docker build ===-------------

FROM splintercommunity/splinter-dev as BUILDER

COPY cli /build/cli
COPY libsplinter /build/libsplinter
COPY services/health /build/services/health
COPY splinterd/ /build/splinterd

# Build splinterd
WORKDIR /build/splinterd
ARG REPO_VERSION
ARG CARGO_ARGS
RUN sed -i -e s/version.*$/version\ =\ \"${REPO_VERSION}\"/ Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION $CARGO_ARGS
RUN mv /build/target/debian/splinter-daemon*.deb /tmp

# Build splinter-cli
WORKDIR /build/cli
ARG REPO_VERSION
ARG CARGO_ARGS
RUN sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${REPO_VERSION}\"/" Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION $CARGO_ARGS
RUN mv /build/target/debian/splinter-cli*.deb /tmp

# -------------=== splinterd docker build ===-------------

FROM ubuntu:bionic

ARG CARGO_ARGS
RUN echo "CARGO_ARGS = '$CARGO_ARGS'" > CARGO_ARGS

COPY --from=builder /tmp/splinter-*.deb /tmp/

RUN apt-get update \
 && dpkg --unpack /tmp/splinter-*.deb \
 && apt-get -f -y install
