#!/bin/bash
# Copyright 2018-2020 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

top_dir=$(cd $(dirname $(dirname $0)) && pwd)

export VERSION=AUTO_STRICT
export REPO_VERSION=$($top_dir/bin/get_version)

export NAMESPACE=${NAMESPACE}

SERVICES="
    gridd
    griddle
    grid-cli
    grid-ui
"

build_docker() {
    for SERVICE in $SERVICES
    do
        echo "Building $SERVICE"
        docker buildx bake -f ci/docker-bake.hcl $SERVICE --push
    done
}

if [ -z $1 ];
then
    # Runs if no arguments are provided
    ISOLATION_ID=$REPO_VERSION
    echo "Publishing release images"
    echo "ISOLATION_ID is: $ISOLATION_ID"
    #Push to dockerhub with the full tag e.g. (1.2.3)
    build_docker
    ISOLATION_ID=${REPO_VERSION} build_docker
    # Push to dockerhub with just major/minor e.g. (1.2)
    ISOLATION_ID=${REPO_VERSION%.*} build_docker
    exit 0
else
    export ISOLATION_ID=$1
    if [ $1 == "experimental" ];
    then
        export CARGO_ARGS=" --features experimental"
    else
        true
    fi
fi
echo "Publishing images for an untagged build"
echo "ISOLATION_ID is: $ISOLATION_ID"

build_docker
