#!/bin/bash
# Copyright 2018-2020 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

top_dir=$(cd $(dirname $(dirname $0)) && pwd)

export VERSION=AUTO_STRICT
export npm_config_sapling_version=$($top_dir/bin/get_version)

docker-compose -f ci/package-sapling.yaml up --build

artifacts upload \
--target-paths saplings \
--working-dir $TRAVIS_BUILD_DIR/build \
$(find build -type f -name *.sapling -printf "%f\n")
