#!/bin/bash
# Copyright 2018-2020 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

top_dir=$(cd $(dirname $(dirname $0)) && pwd)

export VERSION=AUTO_STRICT
export REPO_VERSION=$($top_dir/bin/get_version)

if [ ! -z $TRAVIS_TAG ];
then
    # Runs on tagged builds
    ISOLATION_ID=$REPO_VERSION
    echo "Publishing release images for a tagged build"
    echo "ISOLATION_ID is: $ISOLATION_ID"
    # Push to dockerhub with the full tag e.g. (1.2.3)
    ISOLATION_ID=${REPO_VERSION} docker-compose -f docker-compose.yaml build splinter-ui-alpha
    ISOLATION_ID=${REPO_VERSION} docker-compose -f docker-compose.yaml push splinter-ui-alpha
    # Push to dockerhub with just major/minor e.g. (1.2)
    ISOLATION_ID=${REPO_VERSION%.*} docker-compose -f docker-compose.yaml build splinter-ui-alpha
    ISOLATION_ID=${REPO_VERSION%.*} docker-compose -f docker-compose.yaml push splinter-ui-alpha
    # Push to dockerhub with "latest"
    ISOLATION_ID="latest" docker-compose -f docker-compose.yaml build splinter-ui-alpha
    ISOLATION_ID="latest" docker-compose -f docker-compose.yaml push splinter-ui-alpha
    exit 0
fi

# Runs if build is _not_ a tagged build
if [ -z $1 ]
then
    # If no arguments are provided to the script
    ISOLATION_ID=$REPO_VERSION
else
    ISOLATION_ID=$1
fi
echo "Publishing main images for an untagged build"
echo "ISOLATION_ID is: $ISOLATION_ID"

docker-compose -f docker-compose.yaml build splinter-ui-alpha
docker-compose -f docker-compose.yaml push splinter-ui-alpha
