#!/bin/bash
# Copyright 2018-2020 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Publishes grid-sdk to crates.io.
# $ CARGO_CRED=%yourcargocred% ./ci/publish-crates

top_dir=$(cd $(dirname $(dirname $0)) && pwd)

export VERSION=AUTO_STRICT
export REPO_VERSION=$($top_dir/bin/get_version)

docker build -f ci/publish-grid-sdk-crates -t publish-grid-sdk-crates ci/
docker run \
  --rm \
  -v $(pwd):/project/grid \
  -e REPO_VERSION=$REPO_VERSION \
  -e CARGO_CRED=$CARGO_CRED \
  publish-grid-sdk-crates
