# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM splintercommunity/splinter-dev as BUILDER

# Copy over source files
COPY examples/gameroom/database /build/examples/gameroom/database
COPY protos /build/protos
COPY examples/gameroom/daemon/ /build/examples/gameroom/daemon
COPY libsplinter /build/libsplinter
COPY protos/ /build/protos

# Build the project
WORKDIR /build/examples/gameroom/daemon
ARG REPO_VERSION
RUN sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${REPO_VERSION}\"/" Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION

# -------------=== gameroomd docker build ===-------------
FROM ubuntu:bionic

RUN apt-get update \
 && apt-get install -y \
    curl \
    postgresql-client \
    unzip

COPY --from=BUILDER /build/target/debian/gameroom*.deb /tmp

RUN apt-get update \
 && dpkg -i /tmp/gameroom*.deb || true \
 && apt-get -f -y install

# Fetch the XO smart contract
RUN curl -OLsS https://build.sawtooth.me/job/Sawtooth-Hyperledger/job/sawtooth-sdk-rust/job/master/lastSuccessfulBuild/artifact/build/scar/*zip*/scar.zip

RUN unzip -oj scar.zip \
 && tar -xvf xo_*.scar \
 && rm scar.zip xo_*.scar \
 && mv xo-tp-rust.wasm /var/lib/gameroomd/xo-tp-rust.wasm

CMD ["gameroomd"]
