# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f contracts/pike/Dockerfile-installed-bionic -t sawtooth-pike-tp .

# -------------=== grid pike tp build ===-------------

FROM ubuntu:bionic as grid-pike-tp-builder

ENV VERSION=AUTO_STRICT

RUN apt-get update \
 && apt-get install -y \
 curl \
 gcc \
 git \
 libssl-dev \
 libzmq3-dev \
 pkg-config \
 python3 \
 unzip

# Install Rust
RUN curl https://sh.rustup.rs -sSf > /usr/bin/rustup-init \
 && chmod +x /usr/bin/rustup-init \
 && rustup-init -y

# Install protoc
RUN curl -OLsS https://github.com/google/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip \
    && unzip -o protoc-3.7.1-linux-x86_64.zip -d /usr/local \
    && rm protoc-3.7.1-linux-x86_64.zip

ENV PATH=$PATH:/root/.cargo/bin

RUN cargo install cargo-deb

COPY . /project

WORKDIR /project/contracts/pike

RUN cargo deb

# -------------=== grid pike tp docker build ===-------------

FROM ubuntu:bionic

COPY --from=grid-pike-tp-builder /project/contracts/pike/target/debian/grid-pike-tp*.deb /tmp

RUN apt-get update \
 && dpkg -i /tmp/grid-pike-tp*.deb || true \
 && apt-get -f -y install

CMD ["grid-pike-tp", "-vv"]
