name: Publish Release

on:
  push:
    tags:
      - '*'

env:
  slack-channel: 'alerts'

jobs:

  unit_test_grid:
    if: >-
      github.repository_owner == 'hyperledger'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Display envvars
        run: env

      - name: Install Just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

      - name: Run tests
        run: just ci-test

  publish_docker:
    needs: unit_test_grid
    if: >-
      github.repository_owner == 'hyperledger'
    runs-on: macos-arm
    steps:
      - name: Display envvars
        run: env

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish release to dockerhub
        run: |
          git fetch --tags --force
          ./ci/publish-docker
        env:
          NAMESPACE: ${{ secrets.DOCKER_HUB_NAMESPACE }}/
          VERSION: AUTO_STRICT
          CARGO_TERM_COLOR: always

      - name: Notify Slack of Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  publish_to_crates:
    needs: unit_test_grid
    if: >-
      github.repository_owner == 'hyperledger'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Display envvars
        run: env

      - name: Publish release to crates
        run: |
          git fetch --tags --force
          CARGO_TOKEN=${{ secrets.CARGO_TOKEN }} ./ci/publish-crates

      - name: Notify Slack of Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  build_contracts:
    needs: unit_test_grid
    if: >-
      github.repository_owner == 'hyperledger'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Display envvars
        run: env

      - name: Build smart contracts
        run: |
          git fetch --tags --force
          ./ci/build-contracts

      - uses: actions/upload-artifact@v2
        with:
          name: grid-contracts
          path: grid-contracts.zip

      - name: Notify Slack of Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

